# .gitlab-ci.yml
# Carlos Valdez
# 
# Ensures that `python src/test_data.py` runs correctly.
image: ubuntu

before_script:
  - "apt-get update -y; apt-get install python3.12 python3-pip -y; pip3 install pipenv"
test:
  script:
    - "pipenv install"
    - "pipenv shell"
    - "pipenv run tests"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
