# .gitlab-ci.yml
# Carlos Valdez
# 
# Ensures that `python src/test_data.py` runs correctly.
image: ubuntu

before_script:
  - "apt-get update -y && apt-get install python3 python3-pip -y"
test:
  script:
    - "pip3 install -r requirements.txt"
    - "python3 src/test_data.py"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
