# .gitlab-ci.yml
# Carlos Valdez
# 
# Ensures that `python src/test_data.py` runs correctly.

# The program runs on a Fedora-based Linux distro, so should be tested on a
# Fedora-based image.
image: fedora:latest

before_script:
  - "dnf upgrade -y && dnf install python3.12 pip -y"
test:
  script:
    - "pip install -r requirements.txt"
    - "python src/test_data.py"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
